apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-incus
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: proxy
      app.kubernetes.io/instance: incus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: proxy
        app.kubernetes.io/instance: incus
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: proxy
          image: ghcr.io/beryju/istio-proxy
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
              name: http
          env:
            - name: INT_HOST
              value: "https://optiplex-3090-g3h24n3.prod.beryju.io:8443"
            - name: EXTRA_CONFIG
              value: |
                proxy_set_header Host incus.beryjuio-prod.k8s.beryju.io;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_http_version 1.1;
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-incus
  namespace: istio-system
spec:
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app.kubernetes.io/name: proxy
    app.kubernetes.io/instance: incus
  type: ClusterIP
