apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: umami-secrets
  namespace: analytics
spec:
  secretStoreRef:
    name: vault-kv
    kind: ClusterSecretStore
  target:
    template:
      data:
        values.yaml: |
          umami:
            appSecret: "{{ .secret_key }}"
          postgresql:
            auth:
              password: "{{ .postgres_pwd }}"
  dataFrom:
    - extract:
        key: kv/services/umami
