# prettier-ignore
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: umami
  namespace: analytics
spec:
  chart:
    spec:
      chart: umami
      version: 2.3.3
      sourceRef:
        kind: HelmRepository
        name: umami
        namespace: flux-system
  timeout: 10m0s
  interval: 1h0m0s
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: StatefulSet
              name: umami-postgresql
            patch: |
              - op: add
                path: /spec/volumeClaimTemplates/0/metadata/labels/snapshot.home.arpa~1enabled
                value: "true"
  valuesFrom:
  - kind: Secret
    name: umami-secrets
  values:
    umami:
      forceSSL: true
    resources:
      requests:
        memory: 100Mi
        cpu: 10m
      limits:
        memory: 1Gi
        cpu: "1"
    initContainers:
      waitForDatabase:
        image: proxy.registry.beryju.io/library/busybox:1.38
    ingress:
      enabled: true
      ingressClassName: istio
      hosts:
        - host: analytics.beryju.org
          paths:
            - path: /
              pathType: Prefix
        - host: analytics.beryju.io
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - analytics.beryju.org
            - analytics.beryju.io
          secretName: beryju-io-analytics
    postgresql:
      enabled: true
      image:
        repository: proxy.registry.beryju.io/library/postgres
      metrics:
        enabled: true
        image:
          repository: proxy.registry.beryju.io/prometheuscommunity/postgres-exporter
        serviceMonitor:
          enabled: true
      standalone:
        persistence:
          size: 10Gi
        resources:
          requests:
            memory: 65Mi
            cpu: 15m
          limits:
            memory: 2Gi
            cpu: 1500m
