name: flux-diff

on:
  pull_request:

jobs:
  diffs:
    name: Compute diffs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster_path:
          - clusters/beryjuio-home
          - clusters/beryjuio-oci
          - clusters/beryjuio-prod
    steps:
      - uses: fluxcd/flux2/action@v2.9.0
      - uses: home-operations/flate/action@v0.4.10
        with:
          cache: true
      - id: diff
        env:
          FLATE_OUTPUT: github
          FLATE_BASE: main
          FLATE_PATH: ./${{ matrix.cluster_path }}
        run: |
          diff=$(flate diff all)
          {
            echo 'diff<<EOF'
            echo "${diff}"
            echo 'EOF'
          } >> "${FORGEJO_OUTPUT}"
      - name: PR Comments
        uses: mshick/add-pr-comment@v3
        if: ${{ steps.diff.outputs.diff != '' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message-id: ${{ github.event.pull_request.number }}/${{ matrix.cluster_path }}
          message-failure: Unable to post kustomization diff
          message: |
            ## Cluster ${{ matrix.cluster_path }}

            ---

            <details>

            `````diff
            ${{ steps.diff.outputs.diff }}
            `````

            </details>
